apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: default
  source:
    repoURL: https://github.com/cybozu-go/neco-apps.git
    targetRevision: release
    path: elastic/base
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-system
  ignoreDifferences:
  - group: core
    kind: Secret
    name: webhook-server-secret
    namespace: elastic-system
    jsonPointers:
    - /data
    - /type
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
