apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unbound
  namespace: argocd
  annotations:
    # after metallb
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/cybozu-go/neco-apps.git
    targetRevision: release
    path: unbound/base
  destination:
    server: https://kubernetes.default.svc
    namespace: internet-egress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
