groups:
  - name: argocd-config
    rules:
      - alert: AppOutOfSync
        expr: argocd_app_info{sync_status!="Synced",project="default"} == 1
        for: 20m
        labels:
          severity: minor
        annotations:
          summary: "{{ $labels.name }} is out-of-sync."
          runbook: "See https://github.com/cybozu-go/neco-apps/blob/master/DEVELOPMENT.md#out-of-sync"
      - alert: AllAppMissing
        expr: absent(argocd_app_info{sync_status="Synced",project="default"})
        for: 20m
        labels:
          severity: minor
        annotations:
          summary: "no application is synced."
          runbook: "See https://github.com/cybozu-go/neco-apps/blob/master/DEVELOPMENT.md#out-of-sync"
      - alert: ArgoCDDown
        expr: |
          absent(up{job="argocd"} == 1)
        labels:
          severity: minor
        for: 10m
        annotations:
          summary: ArgoCD has disappeared from Prometheus target discovery.
          runbook: Please consider to find root causes, and solve the problems
