apiVersion: v1
kind: Namespace
metadata:
  name: app-comconv-earthlab
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: maneki-role-binding
  namespace: app-comconv-earthlab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: Group
    name: maneki
    apiGroup: rbac.authorization.k8s.io
