apiVersion: v1
kind: Service
metadata:
  name: unbound-bastion
  namespace: internet-egress
  labels:
    app.kubernetes.io/name: unbound-bastion
  annotations:
    metallb.universe.tf/address-pool: bastion
spec:
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 1053
  selector:
    app.kubernetes.io/name: unbound
  type: LoadBalancer
