apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - common/clusterrole.yaml
  - common/resources.yaml
  - common/psp.yaml
  - ceph-hdd
  - ceph-ssd
images:
  - name: rook/ceph
    newName: quay.io/kfyharukz/rook-ceph
    newTag: 2020-09-18-1
