currentNamespaceOnly: true
enableDiscoveryDaemon: false
csi:
  enableCephfsDriver: false
  pluginPriorityClassName: ""
  provisionerPriorityClassName: ""
image:
  repository: quay.io/kfyharukz/rook-ceph
  tag: 2020-09-18-1
  pullPolicy: IfNotPresent
resources:
  limits:
  requests:
    cpu: 100m
    memory: 256Mi
