currentNamespaceOnly: true
enableDiscoveryDaemon: false
csi:
  enableCephfsDriver: false
  pluginPriorityClassName: ""
  provisionerPriorityClassName: ""
image:
  repository: quay.io/llamerada_jp/rook
  tag: ceph-raw-mode-on-lv-backed-pvc-01
  pullPolicy: IfNotPresent
resources:
  limits:
  requests:
    cpu: 100m
    memory: 256Mi
