apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
spec:
  config:
    server:
      domain: grafana.monitoring.stage0.cybozu-ne.co
      root_url: https://grafana.monitoring.stage0.cybozu-ne.co
