apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- upstream/base/certificates.yaml
- upstream/base/controller.yaml
- upstream/base/crd.yaml
- upstream/base/mutatingwebhooks.yaml
- upstream/base/node.yaml
- upstream/base/provisioner.yaml
- upstream/base/psp.yaml
- upstream/base/scheduler.yaml
- upstream/overlays/daemonset-scheduler/scheduler.yaml
- priorityclass.yaml
- pdb.yaml

patchesStrategicMerge:
- crd.yaml
- node.yaml
- scheduler.yaml

configMapGenerator:
  - name: scheduler-options
    namespace: topolvm-system
    files:
      - ./upstream/base/scheduler-options.yaml

images:
  - name: quay.io/topolvm/topolvm
    newTag: 0.5.2

patchesJSON6902:
- target:
    group: cert-manager.io
    version: v1alpha3
    kind: Issuer
    name: webhook-selfsign
    namespace: topolvm-system
  patch: |-
    - op: replace
      path: /apiVersion
      value: cert-manager.io/v1alpha2
- target:
    group: cert-manager.io
    version: v1alpha3
    kind: Certificate
    name: webhook-ca
    namespace: topolvm-system
  patch: |-
    - op: replace
      path: /apiVersion
      value: cert-manager.io/v1alpha2
- target:
    group: cert-manager.io
    version: v1alpha3
    kind: Issuer
    name: webhook-ca
    namespace: topolvm-system
  patch: |-
    - op: replace
      path: /apiVersion
      value: cert-manager.io/v1alpha2
- target:
    group: cert-manager.io
    version: v1alpha3
    kind: Certificate
    name: mutatingwebhook
    namespace: topolvm-system
  patch: |-
    - op: replace
      path: /apiVersion
      value: cert-manager.io/v1alpha2
