apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus
spec:
  name: middleware.yaml
  datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      url: http://prometheus.monitoring.svc:9090
      version: 1
      isDefault: true
      editable: false
      jsonData:
        tlsSkipVerify: true
        timeInterval: "5s"
