{
 "title": "Memory Usage",
 "tags": [ "node" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage (argocd)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"argocd\"}/1024/1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (elastic-system)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"elastic-system\"}/1024/1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (maneki)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"maneki\"}/1024/1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (external-dns)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"external-dns\"}/1024/1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (monitoring)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"monitoring\", pod!~\"machines-endpoints-(.*)\"}/1024/1024",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum (container_memory_usage_bytes{namespace=\"monitoring\", pod=~\"machines-endpoints-(.*)\"})/1024/1024",
     "legendFormat": "machines-endpoints"
    }
   ]
  },
  {
   "title": "Memory Usage (internet-egress)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"internet-egress\"}/1024/1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (ingress)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=~\"ingress-.*\"}/1024/1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (teleport)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"teleport\"}/1024/1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (kube-system)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"kube-system\"}/1024/1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (metallb-system)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"metallb-system\"}/1024/1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (topolvm-system)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"topolvm-system\"}/1024/1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (demo)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"demo\"}/1024/1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (default)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"default\"}/1024/1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (kube-public)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"kube-public\"}/1024/1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (kube-node-lease)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"kube-node-lease\"}/1024/1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (sandbox)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"sandbox\"}/1024/1024",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}