apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-health
  namespace: monitoring
  labels:
    app.kubernetes.io/name: ingress-health
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-health
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingress-health
    spec:
      containers:
      - name: ingress-health
        args:
          - --listen=:8080
        image: quay.io/cybozu/testhttpd:0.1.0
        ports:
          - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
      terminationGracePeriodSeconds: 10
